---
version: "2.4"
services:

  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=timetrex
      - POSTGRESQL_PASSWORD=p@ssword
      - POSTGRESQL_DATABASE=timetrex
    ports:
      - "5432:5432"
    networks:
      - timetrex

  app:
    image: penguintech/timetrex
    build: .
    environment:
      - DATABASE_HOST=postgresql
      - URL=https://127.0.0.1
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgresql
    networks:
      - timetrex
    healthcheck:
      test: ["CMD", "ansible-playbook", "oldupstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  timetrex:
